export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';

export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';

export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';

export const TOGGLE_STATUS_TODO_ITEM = 'TOGGLE_STATUS_TODO_ITEM';

export const SHOW_FILTERED_TODO_ITEMS = 'SHOW_FILTERED_TODO_ITEMS';

export const SHOW_MODAL_AREA = 'SHOW_MODAL_AREA';

export const HIDE_MODAL_AREA = 'HIDE_MODAL_AREA';
